
name: Publish

on:
  pull_request:
  push:
    branches: [main, develop]
    tags: ['*']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BASE_IMG_REPO: project8/luna_base
  BASE_IMG_TAG: v1.3.3
  DO_DOCKER_PUSH: ${{ github.event_name == 'push' && ( contains(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop' ) }}

jobs:

  init:
    runs-on: ubuntu-latest
    outputs:
      luna_base_version: ${{ steps.setversion.outputs.luna_base_version }}
      katydid_version: ${{ steps.setversion.outputs.katydid_version }}
      locust_version: ${{ steps.setversion.outputs.locust_version }}
      mermithid_version: ${{ steps.setversion.outputs.mermithid_version }}

    steps:
      - name: Set Versions
        id: setversion
        run: |
          git clone https://github.com/project8/luna_base.git
          cd luna_base
          echo "::set-output name=luna_base_version::$(git describe --abbrev=0 --tags)"
          cd ..
          
          git clone https://github.com/project8/katydid.git
          cd katydid
          echo "::set-output name=katydid_version::$(git describe --abbrev=0 --tags)"
          cd ..
          
          git clone https://github.com/project8/locust_mc.git
          cd locust_mc
          echo "::set-output name=locust_version::$(git describe --abbrev=0 --tags)"
          cd ..
          
          git clone https://github.com/project8/mermithid.git
          cd mermithid
          echo "::set-output name=mermithid_version::$(git describe --abbrev=0 --tags)"
          cd ..

  publish:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [init]
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # type=semver,pattern={{raw}} -- used only on push tag events; gives us the `vX.Y.Z`` tag
      # ref,event=branch -- used only on pull_request events; gives us a `pr-X`` tag
      # ref, event=pr -- used only on push events; gives us main and develop tags
      # ref, raw,value=latest,... -- restricted to only main-branch push events; gives us the `latest` tag
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          flavor: |
            latest=auto
            suffix=${{ matrix.tag-suffix }},onlatest=true
          tags: |
            type=semver,pattern={{raw}}
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver: docker

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Luna
        id: build
        uses: docker/build-push-action@v2
        with:
          context: P8Compute/
          file: P8Compute/Dockerfile
          build-args: |
            img_repo=${{ env.REGISTRY }}/${{ env.BASE_IMG_REPO }}
            img_tag=${{ needs.init.outputs.luna_base_version }}
            locust_tag=${{ needs.init.outputs.locust_version }}
            katydid_tag=${{ needs.init.outputs.katydid_version }}
            mermithid_tag=${{ needs.init.outputs.mermithid_version }}
            p8compute_tag=${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Build Luna-Jupyter
        id: build_jupyter
        uses: docker/build-push-action@v2
        with:
          context: P8CJupyter/
          file: P8CJupyter/Dockerfile
          build-args: |
            img_repo=${{ env.REGISTRY }}/${{ github.repository }}
            img_tag=${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
          tags: ${{ steps.docker_meta.outputs.tags }}-jupyter

      - name: Push images
        if: ${{ env.DO_DOCKER_PUSH }}
        run: |
          docker push -a ${{ env.REGISTRY }}/${{ github.repository }}
